export default {
  show: state => state.show,
  tabIndex: state => state.tabIndex,
  disabled: state => state.disabled,
  // Select
  jobOp: state => state.jobOp,
  genderOp: state => state.genderOp,
  disOp: state => state.disOp,
  cadOp: state => state.cadOp,
  nationalityOp: state => state.nationalityOp,
  typeOp: state => state.typeOp,
  phoneOp: state => state.phoneOp,
  phoneProps: state => state.phoneProps,
  /// Organization values
  orgDataInfo: state => state.orgDataInfo,
  orgAdminInfo: state => state.orgAdminInfo,
  orgLogo: state => state.orgLogo,
  orgName: state => state.orgName,
  orgDisName: state => state.orgDisName,
  orgRegNumber: state => state.orgRegNumber,
  orgPrefix: state => state.orgPrefix,
  orgType: state => state.orgType,
  // contact
  orgContact: state => state.orgContact,
  orgPhone: state => state.orgPhone,
  orgEmail: state => state.orgEmail,
  orgWebsite: state => state.orgWebsite,
  // location
  orgDis: state => state.orgDis,
  orgCad: state => state.orgCad,
  orgAddress: state => state.orgAddress,
  // other:
  orgDescription: state => state.orgDescription,
  /// organization administrator
  userLogo: state => state.userLogo,
  userName: state => state.userName,
  userFN: state => state.userFN,
  userLN: state => state.userLN,
  userFNAR: state => state.userFNAR,
  userLNAR: state => state.userLNAR,
  userGender: state => state.userGender,
  userNat: state => state.userNat,
  userDOB: state => state.userDOB,
  userEmail: state => state.userEmail,
  userPhone: state => state.userPhone,
  userJob: state => state.userJob,
  userBio: state => state.userBio,
  userAddress: state => state.userAddress,
}
