export default {
  // Options
  referral: state => state.referral,
  governorate: state => state.governorate,
  district: state => state.district,
  type: state => state.type,
  municipality: state => state.municipality,
  nationality: state => state.nationality,
  gender: state => state.gender,
  priority: state => state.priority,
  caregiver: state => state.caregiver,
  delivery_status: state => state.delivery_status,
  decision: state => state.decision,
  job_title: state => state.job_title,
  organization: state => state.organization,
  org_type: state => state.org_type,
  orgJobOptions: state => state.orgJobOptions,
  org_status: state => state.org_status,
  pcr_result: state => state.pcr_result,
  employment: state => state.employment,
  family_relation: state => state.family_relation,
  inv_warehouse: state => state.inv_warehouse,
  phn_issues: state => state.phn_issues,
  rolesProject: state => state.rolesProject,
  // Phone
  phoneProps: state => state.phoneProps,
  phoneOptions: state => state.phoneOptions,
  organization_data: state => state.organization_data,
  feedback: state => state.feedback,
}
