export default {
  saved: false,
  show: false,
  case_id: null,
  case_code: null,
  org: null,
  fullname: null,
  code: null,
  receiveItem: null,
  reciveInclude: null,
  receiveItemDate: null,
  receiveItemAccept: null,
  notAccept: null,
  receiveItemAcceptFam: null,
  notAcceptFam: null,
  ReciveAwerness: null,
  ReciveAwernessuseful: null,
  ReciveAwernessAccept: null,
  OtherInfo: null,
  OtherItem: null,
  TakeToOther: null,
  OtherComment: null,
  TeamReat: null,
  value: null,
}
