export default {
  saved: false,
  show: false,
  //
  items: [],
  itemField: [
    { key: 'id', label: 'ID' },
    { key: 'error', label: 'Error Message' },
    { key: 'resdtype', label: 'Residential Type' },
    { key: 'cadaster', label: 'Cadaster' },
    { key: 'pcode', label: 'P-Code', class: 'code' },
    { key: 'nofrt', label: 'Number of families in Residence Total' },
    { key: 'husbandfm1', label: 'Husband Name(Family1)', class: 'full_name' },
    { key: 'wifefm1', label: 'Wife Name(Family1)', class: 'full_name' },
    { key: 'phonefm1', label: 'Phone(Family1)' },
    { key: 'unhcrfm1', label: 'UNHCR(Family1)' },
    { key: 'husbandfm2', label: 'Husband Name(Family2)', class: 'full_name' },
    { key: 'wifefm2', label: 'Wife Name(Family2)', class: 'full_name' },
    { key: 'phonefm2', label: 'Phone(Family2)' },
    { key: 'unhcrfm2', label: 'UNHCR(Family2)' },
    { key: 'husbandfm3', label: 'Husband Name(Family3)', class: 'full_name' },
    { key: 'wifefm3', label: 'Wife Name(Family3)', class: 'full_name' },
    { key: 'phonefm3', label: 'Phone(Family3)' },
    { key: 'unhcrfm3', label: 'UNHCR(Family3)' },
    { key: 'husbandfm4', label: 'Husband Name(Family4)', class: 'full_name' },
    { key: 'wifefm4', label: 'Wife Name(Family4)', class: 'full_name' },
    { key: 'phonefm4', label: 'Phone(Family4)' },
    { key: 'unhcrfm4', label: 'UNHCR(Family4)' },

  ],
  //
  json_fields: {
    'Error Message': 'error',
    'Residential Type': 'resdtype',
    Cadaster: 'cadaster',
    'P-Code': 'pcode',
    'Husband Name': 'husband',
    'Wife Name': 'wife',
    'Number Of Individuals for all Families': 'nof',
    'Number of families in Residence': 'nor',
    Latitude: 'latitude',
    Longitude: 'longitude',
    Address: 'address',
  },
}
