export default {
  saved: false,
  show: false,
  //
  typeOptions: [],
  cadOptions: [],
  issOptions: [],
  // Filters
  priority_period: 0,
  priority_interval: 0,

  fullname: null,
  country: 'LB(961)',
  countryid: 1,
  phone: null,
  pcr_date: null,
  referral: null,
  district: null,
  governorate: null,
  type: null,
  iss: null,
  cadaster: null,
  phoneOp: {
    phone: true,
    phoneRegionCode: 'SY',
    placeholder: '70 123 456',
    options: [
      {
        id: 'LB',
        text: 'LB(961)',
        value: 1,
        title: 'Lebanon (961)',
      },
      {
        id: 'SY',
        text: 'SY(963)',
        value: 2,
        title: 'Syria (963)',
      },
    ],
  },
  //
  items: [],
  itemField: [
    { key: 'id', label: 'ID' },
    { key: 'code', label: 'Code', class: 'code' },
    { key: 'referral', label: 'Referral', class: 'referral' },
    { key: 'name', label: 'Full Name', class: 'full_name' },
    { key: 'nationality', label: 'Nationality' },
    { key: 'phone', label: 'Phone', class: 'phone' },
    { key: 'governorate', label: 'Governorate', class: 'governorate' },
    { key: 'district', label: 'District', class: 'district' },
    { key: 'type', label: 'Type', class: 'type' },
    { key: 'cadaster', label: 'cadaster', class: 'cadaster' },
    { key: 'iss', label: 'Settlement', class: 'iss' },
    { key: 'priority', label: 'Priority' },
    { key: 'pcr_date', label: 'PCR Date', class: 'pcr_date' },
    { key: 'action', label: 'Action' },
  ],
  //
  json_fields: {
    'Error Message': 'error',
    'Residential Type': 'resdtype',
    Cadaster: 'cadaster',
    'P-Code': 'pcode',
    'Husband Name': 'husband',
    'Wife Name': 'wife',
    'Number Of Individuals for all Families': 'nof',
    'Number of families in Residence': 'nor',
    Latitude: 'latitude',
    Longitude: 'longitude',
    Address: 'address',
  },
  items_blc: [],
  itemField_blc: [
    { key: 'id', label: 'ID' },
    { key: 'error', label: 'Error Message' },
    { key: 'resdtype', label: 'Residential Type' },
    { key: 'cadaster', label: 'Cadaster' },
    { key: 'pcode', label: 'P-Code', class: 'code' },
    { key: 'husband', label: 'Husband Name', class: 'full_name' },
    { key: 'wife', label: 'Wife Name', class: 'full_name' },
    { key: 'phone', label: 'Phone' },
    { key: 'nof', label: 'Number Of Individuals for all Families' },
    { key: 'nor', label: 'Number of families in Residence' },
    { key: 'latitude', label: 'Latitude' },
    { key: 'longitude', label: 'Longitude' },
    { key: 'address', label: 'Address' },
  ],
}
