export default [
  {
    id: 'fullname',
    title: 'الاسم الثلاثي',
    subtitle: 'الرجاء إدخال المعلومات باللغة العربية',
    value: null,
    req: true,
    rule: 'fullname',
    placeholder: 'ادخل اسمك الكامل',
  },
  {
    id: 'fathername',
    title: 'الاسم الاب',
    subtitle: 'الرجاء إدخال المعلومات باللغة العربية',
    value: null,
    rule: 'name',
    req: true,
    placeholder: 'ادخل اسم الاب',
  },
  {
    id: 'mothername',
    title: 'الاسم الام',
    subtitle: 'الرجاء إدخال المعلومات باللغة العربية',
    value: null,
    req: true,
    rule: 'name',
    placeholder: 'ادخل اسم الام',
  },
  {
    id: 'Malecount',
    title: 'عدد الذكور في المنزل',
    subtitle: 'ادخل عدد افراد عائلتك الذكور من ضمنهم انت',
    value: null,
    rule: null,
    placeholder: 'ادخل عدد الذكور',
    req: true,
    type: 'CardInputNumber',
  },
  {
    id: 'Femalecount',
    title: 'عدد الاناث في المنزل',
    subtitle: 'ادخل عدد افراد عائلتك الإناث من ضمنهم انت',
    value: null,
    rule: null,
    placeholder: 'ادخل عددالإناث',
    req: true,
    type: 'CardInputNumber',
  },
  {
    id: 'childcount',
    title: 'عدد الاطفال دون الـ 15 سنة',
    subtitle: 'ادخل عدد افراد عائلتك الاطفال من ضمنهم انت',
    value: null,
    rule: null,
    placeholder: 'ادخل عدد الاطفال',
    req: true,
    type: 'CardInputNumber',
  },
  {
    id: 'phone',
    title: 'رقم الهاتف',
    value: null,
    rule: 'phonelb',
    req: true,
    type: 'CardInputPhone',
    placeholder: 'ادخل رقم هاتفك للتواصل معك',
  },
  {
    id: 'nationality',
    title: 'الجنسية',
    subtitle: null,
    value: null,
    req: true,
    type: 'CardInputRadio',
    rule: null,
    options: [
      { text: 'لبناني', value: '1' },
      { text: 'سوري', value: '2' },
      { text: 'فلسطيني', value: '3' },
      { text: 'اخر', value: '4' },
    ],
  },
  {
    id: 'injurydate',
    title: 'تاريخ الإصابة',
    subtitle: 'تاريخ الإصابة',
    value: null,
    rule: null,
    req: true,
    placeholder: 'ادخل تاريخ اصابتك',
    type: 'CardInputDate',
  },
  {
    id: 'uploadimage',
    title: 'صورة عن نتيجة الفحص',
    subtitle: 'يرجى أخذ الصورة بشكل واضح (الاسم - التاريخ - النتيجة)',
    value: null,
    placeholder: 'اختار الصورة',
    req: true,
    type: 'CardInputFile',
  },
  {
    id: 'question1',
    title: 'هل تلتزمون بالحجر في المنزل؟',
    subtitle: null,
    value: null,
    req: true,
    type: 'CardInputRadio',
    options: [
      { text: 'نعم', value: '1' },
      { text: 'لا', value: '2' },
    ],
  },
  {
    id: 'gov',
    title: 'المحافظة',
    subtitle: 'الرجاء إختيار المحافظة',
    value: null,
    req: true,
    type: 'CardInputCad',
  },
  {
    id: 'address',
    title: 'العنوان',
    subtitle: 'إسم الحي, الشارع، البناية، الطابق، مقابل...؟',
    value: null,
    req: true,
    rule: 'fullname',
    placeholder: 'العنوان',
  },
  {
    id: 'map',
    title: 'تحديد موقعك عالخريطة',
    value: null,
    req: true,
    rule: null,
    type: 'CardInputMap',
    size: null,
  },
]
