export default {
  title: 'أهلاً بكم ببرنامج RDMS !',
  description: `
  إن كنتم مصابين بفيروس كورونا، بحاجة لأدوات التعقيم و التنظيف، و لا تتعدى اصابتكم السبعة ايام، الرجاء ادخال المعلومات المطلوبة ادناه بشكل صحيح و باللغة العربية، وإلا سيعتبر طلبكم ملغى. 
  يرجى الاخذ بعين الاعتبار ان أدوات التعقيم تصل للعائلة الواحدة في بيت واحد، بغض النظر عن عدد افرادها.
  ملاحظة: ان هذه المساعدة تقدّم للاشخاص المحتاجين، و الكمية محدودة، كما ان اعطائها لعائلة، سيحرم اخرى. نرجوا عدم طلبها الا ان كنتم بحاجة ماسة للحصول عليها.
  شكرا لتعاونكم.`,
  res: null,
  case: null,
  show: false,
  des_code:
        'لقد تم تسجيل حسابكم من قبلنا الرجاء اكمال جميع معلوماتك بشكل صحيح إن كود تسجيلك:',
  des_rep:
        'لقد تم تسجيل معلوماتكم من قبل يمكنكم رؤية تقدم الحالة الخاصة بكم:',
  // Selected
  //
  governorateOption: [],
  disOption: [],
  typeOptions: [],
  cadOptions: [],
  issOptions: [],
  // Filters
  referral: null,
  governorate: null,
  district: null,
  type: null,
  iss: null,
  cadaster: null,
  priority_period: 0,
  grace_period: 0,
  priority_interval: 0,
  // municipality: null,
  nationality: null,
  gender: null,
  employment: null,
  caregiver: null,
  priority: null,
  validated: null,
  phoneissue: null,
  photo: null,
  //
  items: {
    Head_hhold: null,
    active: null,
    address_latitude: null,
    address_longitude: null,
    adresstext: null,
    cadastre_id: null,
    caregiver: null,
    case_code: null,
    case_id: null,
    case_phone: null,
    casse_duration: null,
    comm_assigned: null,
    created_date: null,
    current_status: null,
    delivery_date: null,
    delivery_status: null,
    district_id: null,
    dlvry_assigned: null,
    empl_type: null,
    employed: 0,
    family_members: 0,
    final_decision: null,
    full_name: null,
    isolation_room: 0,
    monthly_payments: 0,
    nationality_id: null,
    org_id: null,
    priority_level: null,
    progress_date: null,
    progress_scoring: null,
    proj_id: null,
    referral_date: null,
    referral_id: null,
  },
  itemsrec: {
    awareness_done: null,
    awareness_token: null,
    case_date: null,
    case_id: null,
    case_notes: null,
    com_inprogress: null,
    com_status: null,
    monitoring_done: null,
    monitoring_token: null,
    pcr_date: null,
    pcr_photo: null,
    pcr_result: null,
    referral_id: null,
    referral_ref_number: null,
  },
  itemsfamily: {
    case_id: null,
    comments: null,
    yng_child_count: 0,
    child_count: 0,
    young_count: 0,
    teenager_count: 0,
    adult_count: 0,
    elderly_count: 0,
    female_count: 0,
    gender: null,
    infected_count: 1,
    male_count: 0,
    pregnant: 0,
  },
  country: {
    id: 1,
    text: 'LB(961)',
    number: null,
  },
  // save
  resp: [],
}
